# fly.toml app configuration file generated for hexaorzo-vaultwarden on 2025-05-16T02:01:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fieldofview'
primary_region = 'hkg'

[build]

[deploy]
  strategy = 'immediate'

[[mounts]]
  source = 'fov_data'
  destination = '/data'
  initial_size = '3GB'
  processes = ['app']

[[services]]
  auto_stop_machines = "off"
  auto_start_machines = true
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
[services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[[services.ports]]
  force_https = true
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[vm]]
  size = 'shared-cpu-1x'
  memory = '768mb'

